# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_lecturer.Lecturer')),
            ],
            options={
                'verbose_name': 'Dan\u0131\u015fman',
                'verbose_name_plural': 'Dan\u0131\u015fmanlar',
            },
        ),
    ]
