# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
