# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('obs_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join_year',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 14, 43, 5, 198666, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='students'),
        ),
    ]
