# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_student', '0002_auto_20161224_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.CharField(max_length=4),
        ),
    ]
