# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.CharField(max_length=50)),
                ('finish_date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
            },
        ),
    ]
