# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_student', '0003_auto_20161224_1454'),
        ('obs_offered_course', '0004_remove_offeredcourse_active_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_status', models.BooleanField(default=False)),
                ('offered_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_offered_course.OfferedCourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_student.Student')),
            ],
            options={
                'verbose_name': 'Öğrenci Tarafından Seçilen Ders',
                'verbose_name_plural': 'Öğrenci Tarafından Seçilen Dersler',
            },
        ),
    ]
