# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='advisor_status',
            new_name='advisor_statuss',
        ),
    ]
