# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_course', '0003_auto_20161224_1338'),
        ('obs_semester', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_year', models.CharField(max_length=12, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_course.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_semester.Semester')),
            ],
            options={
                'verbose_name': 'Açılan Ders',
                'verbose_name_plural': 'Açılan Dersler',
            },
        ),
    ]
