# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_offered_course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeredcourse',
            old_name='active_year',
            new_name='active_years',
        ),
    ]
