# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_offered_course', '0002_auto_20161226_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredcourse',
            name='active_year',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
