# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_offered_course', '0003_offeredcourse_active_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredcourse',
            name='active_years',
        ),
    ]
