# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('obs_department', '0001_initial'),
        ('obs_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 13, 35, 30, 956852, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
