# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_course', '0005_auto_20161226_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obs_department.Department'),
        ),
    ]
